# camera_map:
#   camera_head_main_rgb: "FLIR-Blackfly S BFS-PGE-50S5C-25260985"
#   camera_head_main_right_rgb: "FLIR-Blackfly S BFS-PGE-50S5C-25272263"
#   camera_head_ultrawide_rgb: "FLIR-Blackfly S BFS-PGE-50S5C-25260989"
#   camera_left_main_rgb: "FLIR-Blackfly S BFS-PGE-23S3C-24260091"
#   camera_right_main_rgb: "FLIR-Blackfly S BFS-PGE-23S3C-24260092"

# after swapping the head and wrist cameras
camera_map:
  camera_left_main_rgb: "FLIR-Blackfly S BFS-PGE-50S5C-25260985"
  camera_right_main_rgb: "FLIR-Blackfly S BFS-PGE-50S5C-25272263"
  camera_head_main_rgb: "FLIR-Blackfly S BFS-PGE-23S3C-24260091"
  camera_head_main_right_rgb: "FLIR-Blackfly S BFS-PGE-23S3C-24260092"

frame_rate: 30.0
binning: [4, 4]
pixel_format: PIXEL_FORMAT_BGR_8_PACKED
buffer_size: 16
mock_mode: false
mock_resolution: [720, 1280]
init_timeout: 4.0

viewer:
  backend: auto
  refresh_hz: 15.0
  scale: null
  max_height: 800
  horizon: 1
